function rows = iqcot_r027_proxy_table_in_loop_validation(runSimulink, planMode, maxCases, startRow)
%IQCOT_R027_PROXY_TABLE_IN_LOOP_VALIDATION Run or dry-run R027 proxy table-in-loop cases.
%
% Default dry run:
%   iqcot_r027_proxy_table_in_loop_validation(false)
%
% Priority switching validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "priority")
%
% R030 dense-anchor challenge validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r030_challenge")
%
% R031 tightened B_epsilon^sw minimal held-out validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r031_minimal")
%
% R032 delay-aware B_epsilon^sw band validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r032_delay_band")
%
% R034 transition-pocket validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r034_transition_pocket")
%
% R036 dense-paired boundary validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r036_dense_pair")
%
% R037 minimal extrapolation boundary validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "r037_minimal_extrapolation")
%
% Limited smoke validation:
%   iqcot_r027_proxy_table_in_loop_validation(true, "priority", 12)
%
% Resume a later chunk without overwriting earlier results:
%   iqcot_r027_proxy_table_in_loop_validation(true, "priority", 12, 7)
%
% This runner reads the R027 CSV generated by
% iqcot_r027_proxy_table_in_loop_plan.py, or compatible later validation
% plans such as R030/R031/R032/R034/R036/R037. It uses only the derived model:
%   E:/Desktop/codex/output/simulink_iek/four_phase_iek_dynamic_load_refslew.slx
%
% It does not save or directly edit any SLX file. The AI layer is represented
% as a low-rate supervisory T_slew scheduler; IQCOT remains the inner loop.

clc;

if nargin < 1 || isempty(runSimulink)
    runSimulink = false;
end
if nargin < 2 || isempty(planMode)
    planMode = "priority";
end
if nargin < 3
    maxCases = [];
end
if nargin < 4 || isempty(startRow)
    startRow = 1;
end
planMode = string(planMode);
startRow = max(1, round(double(startRow)));

setappdata(0, "iqcot_r027_run_simulink", runSimulink);
setappdata(0, "iqcot_r027_plan_mode", planMode);
setappdata(0, "iqcot_r027_max_cases", maxCases);
setappdata(0, "iqcot_r027_start_row", startRow);

initRoot = "E:\Desktop\4cot\versions\v0027_20260611_135822_iqcot_optimized_final_cn_docs";
run(fullfile(initRoot, "init_four_phase_cot_sync.m"));

runSimulink = getappdata(0, "iqcot_r027_run_simulink");
planMode = getappdata(0, "iqcot_r027_plan_mode");
maxCases = getappdata(0, "iqcot_r027_max_cases");
startRow = getappdata(0, "iqcot_r027_start_row");
rmappdata(0, "iqcot_r027_run_simulink");
rmappdata(0, "iqcot_r027_plan_mode");
rmappdata(0, "iqcot_r027_max_cases");
rmappdata(0, "iqcot_r027_start_row");

srcRoot = "E:\Desktop\4cot\versions\v0027_20260611_135822_iqcot_optimized_final_cn_docs";
modelRoot = "E:\Desktop\codex\output\simulink_iek";
outputRoot = "E:\Desktop\codex\output";
figureRoot = fullfile(outputRoot, "figures");
if ~exist(figureRoot, "dir")
    mkdir(figureRoot);
end
addpath(outputRoot);
addpath(srcRoot);

localVars = whos;
for varIdx = 1:numel(localVars)
    varName = localVars(varIdx).name;
    if varName ~= "localVars" && varName ~= "varIdx"
        assignin("base", varName, eval(varName));
    end
end

model = "four_phase_iek_dynamic_load_refslew";
modelFile = fullfile(modelRoot, model + ".slx");
if ~exist(modelFile, "file")
    error("Derived model not found: %s", modelFile);
end

plan = loadR027Plan(outputRoot, planMode);
fullPlanHeight = height(plan);
if startRow > fullPlanHeight
    error("startRow %d exceeds plan height %d.", startRow, fullPlanHeight);
end
if isempty(maxCases)
    endRow = fullPlanHeight;
else
    endRow = min(fullPlanHeight, startRow + round(double(maxCases)) - 1);
end
plan = plan(startRow:endRow, :);
runLabel = makeRunLabel(planMode, startRow, endRow, fullPlanHeight);

planOut = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_matlab_plan_" + runLabel + ".csv");
writetable(plan, planOut);

if ~runSimulink
    writeR027DryRunReport(plan, planOut, outputRoot, runLabel);
    fprintf("R027_TABLE_IN_LOOP_PLAN=%s\n", planOut);
    fprintf("Dry run only. To run switching validation, call:\n");
    fprintf("  iqcot_r027_proxy_table_in_loop_validation(true, ""%s"", [], 1)\n", planMode);
    rows = plan;
    return;
end

oldFolder = pwd;
cleanupFolder = onCleanup(@() cd(oldFolder));
cd(modelRoot);

load_system(modelFile);
modelCleanup = onCleanup(@() close_system(model, 0));
instrumentSignals(model);

common = makeCommon();
baseLoadA = 40;
rows = table();
for k = 1:height(plan)
    spec = makeR027Spec(baseLoadA, plan.target_load_A(k), ...
        plan.selected_ref_slew_us(k), plan.ref_start_delay_us_for_simulink(k), common);
    fprintf("R027 case %s: %s, %.1f A -> %.6g A, %s, slew %.3f us, delay %.3f us\n", ...
        string(plan.r027_case_id(k)), string(plan.policy(k)), baseLoadA, ...
        spec.load_A, string(plan.objective(k)), spec.ref_slew_us, spec.ref_start_delay_us);
    try
        out = runDelayedSlewCase(model, spec, common);
        logs = out.logsout;
        baseMetrics = preStepMetrics(logs, common, baseLoadA);
        metrics = transientMetrics(logs, spec, common, baseMetrics);
        rows = [rows; r027RowFromMetrics(plan(k, :), spec, metrics)]; %#ok<AGROW>
    catch ME
        detailedMessage = compactErrorReport(ME);
        rows = [rows; r027FailureRow(plan(k, :), spec, detailedMessage)]; %#ok<AGROW>
        warning("iqcot:R027ProxyTableCaseFailed", "Case failed: %s", detailedMessage);
    end
end
rows = addSwitchingRegret(rows);

resultPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_results_" + runLabel + ".csv");
policyPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_policy_eval_" + runLabel + ".csv");
reportPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_switching_report_" + runLabel + ".md");
figurePath = fullfile(figureRoot, "fig34_r027_proxy_table_in_loop_" + runLabel + ".png");
writetable(rows, resultPath);
policyEval = summarizeR027Policies(rows);
writetable(policyEval, policyPath);
writeR027SwitchingReport(rows, policyEval, resultPath, policyPath, reportPath, runLabel);
makeR027PolicyPlot(policyEval, figurePath);

fprintf("R027_TABLE_IN_LOOP_RESULTS=%s\n", resultPath);
fprintf("R027_TABLE_IN_LOOP_POLICY_EVAL=%s\n", policyPath);
fprintf("R027_TABLE_IN_LOOP_SWITCHING_REPORT=%s\n", reportPath);
fprintf("R027_TABLE_IN_LOOP_FIGURE=%s\n", figurePath);
end

function plan = loadR027Plan(outputRoot, planMode)
if planMode == "full"
    planPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_plan.csv");
elseif planMode == "priority"
    planPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_priority_plan.csv");
elseif planMode == "r030_challenge"
    planPath = fullfile(outputRoot, "iqcot_r030_dense_anchor_challenge_plan.csv");
elseif planMode == "r031_minimal"
    planPath = fullfile(outputRoot, "iqcot_r031_minimal_validation_plan.csv");
elseif planMode == "r032_delay_band"
    planPath = fullfile(outputRoot, "iqcot_r032_next_validation_plan.csv");
elseif planMode == "r034_transition_pocket"
    planPath = fullfile(outputRoot, "iqcot_r034_transition_pocket_validation_plan.csv");
elseif planMode == "r036_dense_pair"
    planPath = fullfile(outputRoot, "iqcot_r036_dense_paired_boundary_validation_plan.csv");
elseif planMode == "r037_minimal_extrapolation"
    planPath = fullfile(outputRoot, "iqcot_r037_minimal_extrapolation_validation_plan.csv");
else
    error("Unknown R027 planMode '%s'. Use 'priority', 'full', 'r030_challenge', 'r031_minimal', 'r032_delay_band', 'r034_transition_pocket', 'r036_dense_pair', or 'r037_minimal_extrapolation'.", planMode);
end
if ~exist(planPath, "file")
    error("R027 plan file not found: %s", planPath);
end
opts = detectImportOptions(planPath, "TextType", "string");
plan = readtable(planPath, opts);
if planMode == "r031_minimal"
    plan = adaptR031MinimalPlan(plan);
elseif planMode == "r032_delay_band"
    plan = adaptR032DelayBandPlan(plan);
elseif planMode == "r034_transition_pocket"
    plan = adaptR034TransitionPocketPlan(plan);
elseif planMode == "r036_dense_pair"
    plan = adaptR036DensePairPlan(plan);
elseif planMode == "r037_minimal_extrapolation"
    plan = adaptR037MinimalExtrapolationPlan(plan);
end
end

function plan = adaptR031MinimalPlan(rawPlan)
% Convert the compact R031 held-out matrix to the R027 runner schema.
% This is an adapter only; it does not modify the source CSV.
plan = table();
plan.r027_case_id = rawPlan.r031_case_id;
plan.target_label = rawPlan.target_label;
plan.objective = rawPlan.objective;
plan.policy = repmat("r031_minimal_candidate", height(rawPlan), 1);
plan.source_policy = repmat("r031_tightened_bepsilon_sw", height(rawPlan), 1);
plan.policy_kind = repmat("heldout_validation_candidate", height(rawPlan), 1);
plan.policy_role = repmat("candidate", height(rawPlan), 1);
plan.online_available_inputs_only = true(height(rawPlan), 1);
plan.objective_alpha_settle = rawPlan.objective_alpha_settle;
plan.target_load_A = rawPlan.target_load_A;
plan.load_drop_A = rawPlan.load_drop_A;
plan.selected_ref_slew_us = rawPlan.candidate_ref_slew_us;
plan.realized_ref_slew_us_in_offline_grid = rawPlan.candidate_ref_slew_us;
plan.tau_ai_us = rawPlan.tau_ai_us;
plan.delay_events = ceil(rawPlan.tau_ai_us ./ 0.5);
plan.ref_start_delay_us_for_simulink = rawPlan.tau_ai_us;
plan.delay_mode = repmat("delayed_reference", height(rawPlan), 1);
plan.offline_objective_score = NaN(height(rawPlan), 1);
plan.offline_regret_vs_oracle = NaN(height(rawPlan), 1);
plan.offline_undershoot_mV = NaN(height(rawPlan), 1);
plan.offline_settle_time_us = NaN(height(rawPlan), 1);
plan.offline_skip_count_est = NaN(height(rawPlan), 1);
plan.offline_phase_std_ns = NaN(height(rawPlan), 1);
end

function plan = adaptR032DelayBandPlan(rawPlan)
% Convert the compact R032 delay-band matrix to the R027 runner schema.
% This adapter is schema-only; it does not modify the source CSV or SLX.
plan = table();
plan.r027_case_id = rawPlan.r032_case_id;
plan.target_label = rawPlan.target_label;
plan.objective = rawPlan.objective;
plan.policy = repmat("r032_delay_band_candidate", height(rawPlan), 1);
plan.source_policy = repmat("r032_delay_aware_bepsilon_sw", height(rawPlan), 1);
plan.policy_kind = repmat("boundary_validation_candidate", height(rawPlan), 1);
plan.policy_role = repmat("candidate", height(rawPlan), 1);
plan.online_available_inputs_only = true(height(rawPlan), 1);
plan.objective_alpha_settle = rawPlan.objective_alpha_settle;
plan.target_load_A = rawPlan.target_load_A;
plan.load_drop_A = rawPlan.load_drop_A;
plan.selected_ref_slew_us = rawPlan.candidate_ref_slew_us;
plan.realized_ref_slew_us_in_offline_grid = rawPlan.candidate_ref_slew_us;
plan.tau_ai_us = rawPlan.tau_ai_us;
plan.delay_events = rawPlan.delay_events_est;
plan.ref_start_delay_us_for_simulink = rawPlan.tau_ai_us;
plan.delay_mode = repmat("delayed_reference", height(rawPlan), 1);
plan.offline_objective_score = NaN(height(rawPlan), 1);
plan.offline_regret_vs_oracle = NaN(height(rawPlan), 1);
plan.offline_undershoot_mV = NaN(height(rawPlan), 1);
plan.offline_settle_time_us = NaN(height(rawPlan), 1);
plan.offline_skip_count_est = NaN(height(rawPlan), 1);
plan.offline_phase_std_ns = NaN(height(rawPlan), 1);
end

function plan = adaptR034TransitionPocketPlan(rawPlan)
% Convert the R034 transition-pocket validation matrix to R027 runner schema.
% This adapter is schema-only; it does not modify the source CSV or SLX.
plan = table();
plan.r027_case_id = rawPlan.r034_case_id;
plan.target_label = rawPlan.target_label;
plan.objective = rawPlan.objective;
plan.policy = repmat("r034_transition_pocket_candidate", height(rawPlan), 1);
plan.source_policy = repmat("r034_deployable_risk_predictor", height(rawPlan), 1);
plan.policy_kind = repmat("transition_pocket_validation_candidate", height(rawPlan), 1);
plan.policy_role = repmat("candidate", height(rawPlan), 1);
plan.online_available_inputs_only = true(height(rawPlan), 1);
plan.objective_alpha_settle = rawPlan.objective_alpha_settle;
plan.target_load_A = rawPlan.target_load_A;
plan.load_drop_A = rawPlan.load_drop_A;
plan.selected_ref_slew_us = rawPlan.candidate_ref_slew_us;
plan.realized_ref_slew_us_in_offline_grid = rawPlan.candidate_ref_slew_us;
plan.tau_ai_us = rawPlan.tau_ai_us;
plan.delay_events = rawPlan.delay_events_est;
plan.ref_start_delay_us_for_simulink = rawPlan.tau_ai_us;
plan.delay_mode = repmat("delayed_reference", height(rawPlan), 1);
plan.offline_objective_score = NaN(height(rawPlan), 1);
plan.offline_regret_vs_oracle = NaN(height(rawPlan), 1);
plan.offline_undershoot_mV = NaN(height(rawPlan), 1);
plan.offline_settle_time_us = NaN(height(rawPlan), 1);
plan.offline_skip_count_est = NaN(height(rawPlan), 1);
plan.offline_phase_std_ns = NaN(height(rawPlan), 1);
end

function plan = adaptR036DensePairPlan(rawPlan)
% Convert the R036 dense-paired boundary matrix to R027 runner schema.
% This adapter only adds executable delayed-reference fields; it does not
% modify the source CSV or any SLX model.
plan = table();
plan.r027_case_id = rawPlan.r036_case_id;
plan.target_label = rawPlan.target_label;
plan.objective = rawPlan.objective;
plan.policy = repmat("r036_dense_fallback_pair", height(rawPlan), 1);
plan.source_policy = repmat("r036_dense_paired_boundary", height(rawPlan), 1);
plan.policy_kind = repmat("dense_paired_boundary_validation", height(rawPlan), 1);
plan.policy_role = repmat("dense_fallback", height(rawPlan), 1);
plan.online_available_inputs_only = true(height(rawPlan), 1);
plan.objective_alpha_settle = rawPlan.objective_alpha_settle;
plan.target_load_A = rawPlan.target_load_A;
plan.load_drop_A = rawPlan.load_drop_A;
plan.selected_ref_slew_us = rawPlan.candidate_ref_slew_us;
plan.realized_ref_slew_us_in_offline_grid = rawPlan.candidate_ref_slew_us;
plan.tau_ai_us = rawPlan.tau_ai_us;
plan.delay_events = rawPlan.delay_events_est;
plan.ref_start_delay_us_for_simulink = rawPlan.tau_ai_us;
plan.delay_mode = repmat("delayed_reference", height(rawPlan), 1);
plan.offline_objective_score = NaN(height(rawPlan), 1);
plan.offline_regret_vs_oracle = NaN(height(rawPlan), 1);
plan.offline_undershoot_mV = NaN(height(rawPlan), 1);
plan.offline_settle_time_us = NaN(height(rawPlan), 1);
plan.offline_skip_count_est = NaN(height(rawPlan), 1);
plan.offline_phase_std_ns = NaN(height(rawPlan), 1);
end

function plan = adaptR037MinimalExtrapolationPlan(rawPlan)
% Convert the R037 minimal extrapolation matrix to R027 runner schema.
% This adapter only adds executable delayed-reference fields; it does not
% modify the source CSV or any SLX model.
plan = table();
plan.r027_case_id = rawPlan.r037_case_id;
plan.target_label = rawPlan.target_label;
plan.objective = rawPlan.objective;
plan.policy = repmat("r037_minimal_extrapolation_candidate", height(rawPlan), 1);
plan.source_policy = repmat("r037_short_horizon_rhat", height(rawPlan), 1);
plan.policy_kind = repmat("minimal_extrapolation_boundary_validation", height(rawPlan), 1);
plan.policy_role = repmat("candidate", height(rawPlan), 1);
plan.online_available_inputs_only = true(height(rawPlan), 1);
plan.objective_alpha_settle = rawPlan.objective_alpha_settle;
plan.target_load_A = rawPlan.target_load_A;
plan.load_drop_A = rawPlan.load_drop_A;
plan.selected_ref_slew_us = rawPlan.candidate_ref_slew_us;
plan.realized_ref_slew_us_in_offline_grid = rawPlan.candidate_ref_slew_us;
plan.tau_ai_us = rawPlan.tau_ai_us;
plan.delay_events = rawPlan.delay_events_est;
plan.ref_start_delay_us_for_simulink = rawPlan.tau_ai_us;
plan.delay_mode = repmat("delayed_reference", height(rawPlan), 1);
plan.offline_objective_score = NaN(height(rawPlan), 1);
plan.offline_regret_vs_oracle = NaN(height(rawPlan), 1);
plan.offline_undershoot_mV = NaN(height(rawPlan), 1);
plan.offline_settle_time_us = NaN(height(rawPlan), 1);
plan.offline_skip_count_est = NaN(height(rawPlan), 1);
plan.offline_phase_std_ns = NaN(height(rawPlan), 1);
end

function runLabel = makeRunLabel(planMode, startRow, endRow, fullPlanHeight)
if startRow == 1 && endRow == fullPlanHeight
    runLabel = planMode;
else
    runLabel = sprintf("%s_rows%03d_%03d", planMode, startRow, endRow);
end
runLabel = string(runLabel);
end

function common = makeCommon()
common = struct();
common.lambdaArea = 6e-10;
common.vAreaBias = 2e-3;
common.riArea = 0.5e-3;
common.tStep = 0.45e-3;
common.stopTime = 0.60e-3;
common.postSteadyWindow = 20e-6;
common.preSteadyWindow = 50e-6;
common.maxStep = "5e-9";
common.fastTss = 5e-9;
if evalin("base", "exist('Vo_ref','var')")
    common.voRef = evalin("base", "Vo_ref");
else
    common.voRef = 1.0;
end
if evalin("base", "exist('Tslot','var')")
    common.expectedSlot = evalin("base", "Tslot");
else
    common.expectedSlot = 0.5e-6;
end
end

function spec = makeR027Spec(baseLoadA, targetLoadA, slewUs, delayUs, common)
spec = struct();
spec.controller_mode = "r027_proxy_table_in_loop";
spec.base_load_A = baseLoadA;
spec.load_A = targetLoadA;
spec.effective_load_A = max(targetLoadA, 1e-3);
spec.Rload = common.voRef / spec.effective_load_A;
spec.Iph_initial = baseLoadA / 4;
spec.Iph_final = targetLoadA / 4;
spec.Iph = spec.Iph_final;
spec.ref_slew_us = slewUs;
spec.ref_slew_s = slewUs * 1e-6;
spec.ref_start_delay_us = delayUs;
spec.ref_start_delay_s = delayUs * 1e-6;
spec.Lambda_area = common.lambdaArea;
spec.Lambda_vec = common.lambdaArea * ones(1, 4);
spec.Ton_trim_vec = zeros(1, 4);
spec.Varea_bias = common.vAreaBias;
spec.Ri_area = common.riArea;
end

function out = runDelayedSlewCase(model, spec, common)
in = Simulink.SimulationInput(model);
in = in.setModelParameter( ...
    "StopTime", num2str(common.stopTime, "%.15g"), ...
    "MaxStep", char(common.maxStep), ...
    "SignalLogging", "on", ...
    "SignalLoggingName", "logsout", ...
    "ReturnWorkspaceOutputs", "on");
in = in.setVariable("Tss", common.fastTss);
in = in.setVariable("Iload_initial", spec.base_load_A);
in = in.setVariable("Iload_final", spec.load_A);
in = in.setVariable("t_load_step", common.tStep);
in = in.setVariable("Rload", 1e6);
in = in.setVariable("Iout", spec.base_load_A);
in = in.setVariable("Iph", spec.Iph);
in = in.setVariable("Iph_ref_ts", makeDelayedIphRefTimeseries(spec, common));
in = in.setVariable("Lambda_area", spec.Lambda_area);
in = in.setVariable("Lambda_m2", 0);
for phase = 1:4
    in = in.setVariable("Lambda" + phase, spec.Lambda_vec(phase));
    in = in.setVariable("Ton_trim" + phase, spec.Ton_trim_vec(phase));
end
in = in.setVariable("Varea_bias", spec.Varea_bias);
in = in.setVariable("Ri_area", spec.Ri_area);
in = in.setVariable("Iqcot_enable", 0);
in = in.setVariable("Kiqcot", 0);
out = sim(in);
end

function ts = makeDelayedIphRefTimeseries(spec, common)
slew = max(spec.ref_slew_s, common.fastTss);
start = common.tStep + max(spec.ref_start_delay_s, 0);
finish = start + slew;
if spec.ref_start_delay_s <= 0
    t = [0; common.tStep; finish; common.stopTime];
    y = [spec.Iph_initial; spec.Iph_initial; spec.Iph_final; spec.Iph_final];
else
    t = [0; common.tStep; start; finish; common.stopTime];
    y = [spec.Iph_initial; spec.Iph_initial; spec.Iph_initial; spec.Iph_final; spec.Iph_final];
end
ts = timeseries(y, t);
ts.Name = "Iph_ref_ts";
end

function metrics = preStepMetrics(logs, common, loadA)
steadyStart = common.tStep - common.preSteadyWindow;
metrics = steadyMetrics(logs, steadyStart, common.tStep, loadA);
end

function metrics = steadyMetrics(logs, steadyStart, steadyEnd, loadA)
metrics = struct();
metrics.vout = windowValues(logs, "vout", steadyStart, steadyEnd);
metrics.vout_mean_V = mean(metrics.vout);
metrics.il_mean_A = zeros(1, 4);
for phase = 1:4
    il = windowValues(logs, "il" + phase, steadyStart, steadyEnd);
    metrics.il_mean_A(phase) = mean(il);
end
metrics.il_total_mean_A = sum(metrics.il_mean_A);
metrics.load_error_A = metrics.il_total_mean_A - loadA;
end

function metrics = transientMetrics(logs, spec, common, baseMetrics)
voutSeries = logs.get("vout").Values;
timeAbs = voutSeries.Time;
vout = squeeze(double(voutSeries.Data));
maskPost = timeAbs >= common.tStep;
time = timeAbs(maskPost) - common.tStep;
vout = vout(maskPost);

metrics = struct();
metrics.vout_initial_V = baseMetrics.vout_mean_V;
metrics.vout_peak_V = max(vout);
metrics.vout_min_V = min(vout);
metrics.overshoot_mV = 1e3 * (metrics.vout_peak_V - common.voRef);
metrics.undershoot_mV = 1e3 * (common.voRef - metrics.vout_min_V);
metrics.t_peak_us = 1e6 * time(find(vout == metrics.vout_peak_V, 1, "first"));
metrics.settle_time_us = settleTimeUs(time, vout, common.voRef, 2e-3);

allEdgesAbs = allGateEdges(logs, common.tStep);
allEdges = allEdgesAbs - common.tStep;
metrics.first_gate_edge_us = NaN;
metrics.max_gate_gap_us = NaN;
metrics.skip_count_est = NaN;
if ~isempty(allEdges)
    metrics.first_gate_edge_us = 1e6 * allEdges(1);
    gaps = diff(allEdges);
    if ~isempty(gaps)
        metrics.max_gate_gap_us = 1e6 * max(gaps);
        metrics.skip_count_est = max(0, round(max(gaps) / common.expectedSlot) - 1);
    else
        metrics.skip_count_est = max(0, round(allEdges(1) / common.expectedSlot) - 1);
    end
end

steadyStart = common.stopTime - common.postSteadyWindow;
metrics.final = steadyMetrics(logs, steadyStart, common.stopTime, spec.load_A);
metrics.final_vout_error_mV = 1e3 * (metrics.final.vout_mean_V - common.voRef);
metrics.il_phase_imbalance_A = max(metrics.final.il_mean_A) - min(metrics.final.il_mean_A);
metrics.il_m2_projection_A = dot(metrics.final.il_mean_A - mean(metrics.final.il_mean_A), [1 -1 1 -1]) / 4;
metrics.phase_spacing = phaseSpacingMetrics(logs, steadyStart);

metrics.base_score = abs(metrics.final_vout_error_mV) + metrics.undershoot_mV ...
    + 0.02 * metrics.phase_spacing.std_ns + 2.0 * metrics.skip_count_est;
metrics.score_settle005 = metrics.base_score + 0.05 * metrics.settle_time_us;
metrics.score_settle010 = metrics.base_score + 0.10 * metrics.settle_time_us;
end

function row = r027RowFromMetrics(planRow, spec, m)
selectedObjective = objectiveScoreFromMetrics(planRow.objective, m);
row = table( ...
    true, "", string(planRow.r027_case_id), string(planRow.target_label), ...
    string(planRow.objective), string(planRow.policy), string(planRow.source_policy), ...
    string(planRow.policy_kind), string(planRow.policy_role), boolFromPlanValue(planRow.online_available_inputs_only), ...
    planRow.objective_alpha_settle, planRow.target_load_A, planRow.load_drop_A, ...
    spec.ref_slew_us, planRow.realized_ref_slew_us_in_offline_grid, ...
    planRow.tau_ai_us, planRow.delay_events, spec.ref_start_delay_us, ...
    string(planRow.delay_mode), planRow.offline_objective_score, planRow.offline_regret_vs_oracle, ...
    planRow.offline_undershoot_mV, planRow.offline_settle_time_us, ...
    planRow.offline_skip_count_est, planRow.offline_phase_std_ns, ...
    m.vout_initial_V, m.vout_peak_V, m.vout_min_V, m.overshoot_mV, m.undershoot_mV, ...
    m.t_peak_us, m.settle_time_us, m.first_gate_edge_us, m.max_gate_gap_us, m.skip_count_est, ...
    m.final_vout_error_mV, ...
    m.final.il_mean_A(1), m.final.il_mean_A(2), m.final.il_mean_A(3), m.final.il_mean_A(4), ...
    m.final.il_total_mean_A, m.final.load_error_A, m.il_phase_imbalance_A, m.il_m2_projection_A, ...
    m.phase_spacing.mean_ns, m.phase_spacing.std_ns, m.phase_spacing.sequence_error_fraction, ...
    m.base_score, m.score_settle005, m.score_settle010, selectedObjective, NaN, ...
    'VariableNames', r027ResultVariableNames());
end

function row = r027FailureRow(planRow, spec, message)
row = table( ...
    false, string(message), string(planRow.r027_case_id), string(planRow.target_label), ...
    string(planRow.objective), string(planRow.policy), string(planRow.source_policy), ...
    string(planRow.policy_kind), string(planRow.policy_role), boolFromPlanValue(planRow.online_available_inputs_only), ...
    planRow.objective_alpha_settle, planRow.target_load_A, planRow.load_drop_A, ...
    spec.ref_slew_us, planRow.realized_ref_slew_us_in_offline_grid, ...
    planRow.tau_ai_us, planRow.delay_events, spec.ref_start_delay_us, ...
    string(planRow.delay_mode), planRow.offline_objective_score, planRow.offline_regret_vs_oracle, ...
    planRow.offline_undershoot_mV, planRow.offline_settle_time_us, ...
    planRow.offline_skip_count_est, planRow.offline_phase_std_ns, ...
    NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
    NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
    NaN, NaN, NaN, NaN, NaN, ...
    'VariableNames', r027ResultVariableNames());
end

function value = objectiveScoreFromMetrics(objective, m)
objective = string(objective);
if objective == "base"
    value = m.base_score;
elseif objective == "score_settle005"
    value = m.score_settle005;
elseif objective == "score_settle010"
    value = m.score_settle010;
else
    error("Unknown objective '%s'.", objective);
end
end

function value = boolFromPlanValue(rawValue)
if islogical(rawValue)
    value = rawValue;
elseif isnumeric(rawValue)
    value = rawValue ~= 0;
else
    token = lower(strtrim(string(rawValue)));
    value = token == "true" || token == "1" || token == "yes";
end
end

function rows = addSwitchingRegret(rows)
if isempty(rows) || ~any(rows.success)
    return;
end
rows.switching_regret_vs_best_in_run(:) = NaN;
validIdx = find(rows.success);
keys = rows(validIdx, {'target_label','objective','tau_ai_us'});
[groupIds, ~] = findgroups(keys);
for g = 1:max(groupIds)
    idx = validIdx(groupIds == g);
    bestScore = min(rows.selected_objective_score(idx), [], "omitnan");
    rows.switching_regret_vs_best_in_run(idx) = rows.selected_objective_score(idx) - bestScore;
end
end

function message = compactErrorReport(ME)
message = string(getReport(ME, "extended", "hyperlinks", "off"));
message = regexprep(message, "\s+", " ");
message = extractBefore(message + " ", min(strlength(message) + 1, 1800));
message = strtrim(message);
end

function names = r027ResultVariableNames()
names = {'success','error_message','r027_case_id','target_label','objective', ...
    'policy','source_policy','policy_kind','policy_role','online_available_inputs_only', ...
    'objective_alpha_settle','target_load_A','load_drop_A', ...
    'selected_ref_slew_us','realized_ref_slew_us_in_offline_grid', ...
    'tau_ai_us','delay_events','ref_start_delay_us','delay_mode', ...
    'offline_objective_score','offline_regret_vs_oracle', ...
    'offline_undershoot_mV','offline_settle_time_us','offline_skip_count_est','offline_phase_std_ns', ...
    'vout_initial_V','vout_peak_V','vout_min_V','overshoot_mV','undershoot_mV', ...
    't_peak_us','settle_time_us','first_gate_edge_us','max_gate_gap_us','skip_count_est', ...
    'final_vout_error_mV', ...
    'final_il1_mean_A','final_il2_mean_A','final_il3_mean_A','final_il4_mean_A', ...
    'final_il_total_mean_A','final_load_error_A','final_il_phase_imbalance_A','final_il_m2_projection_A', ...
    'final_phase_spacing_mean_ns','final_phase_spacing_std_ns','final_phase_sequence_error_fraction', ...
    'base_score','score_settle005','score_settle010','selected_objective_score', ...
    'switching_regret_vs_best_in_run'};
end

function values = windowValues(logs, signalName, startTime, endTime)
series = logs.get(char(signalName)).Values;
mask = series.Time >= startTime & series.Time <= endTime;
values = squeeze(double(series.Data(mask)));
end

function tSettle = settleTimeUs(time, signal, ref, band)
tSettle = NaN;
outside = abs(signal - ref) > band;
if ~any(outside)
    tSettle = 0;
    return;
end
lastOutside = find(outside, 1, "last");
if lastOutside < numel(time)
    tSettle = 1e6 * time(lastOutside + 1);
end
end

function allTimes = allGateEdges(logs, startTime)
allTimes = [];
for phase = 1:4
    allTimes = [allTimes; edgeTimes(logs, "qh" + phase, startTime)]; %#ok<AGROW>
end
allTimes = sort(allTimes);
end

function times = edgeTimes(logs, signalName, startTime)
series = logs.get(char(signalName)).Values;
mask = series.Time >= startTime;
time = series.Time(mask);
values = squeeze(double(series.Data(mask)));
times = time(find(diff(values > 0.5) > 0) + 1);
end

function spacing = phaseSpacingMetrics(logs, steadyStart)
allTimes = [];
allPhases = [];
for phase = 1:4
    t = edgeTimes(logs, "qh" + phase, steadyStart);
    allTimes = [allTimes; t(:)]; %#ok<AGROW>
    allPhases = [allPhases; phase * ones(numel(t), 1)]; %#ok<AGROW>
end
[allTimes, order] = sort(allTimes);
allPhases = allPhases(order);
spacing = struct("mean_ns", NaN, "std_ns", NaN, "sequence_error_fraction", NaN);
if numel(allTimes) < 6
    return;
end
dt = diff(allTimes);
spacing.mean_ns = 1e9 * mean(dt);
spacing.std_ns = 1e9 * std(dt);
expectedNext = mod(allPhases(1:end-1), 4) + 1;
spacing.sequence_error_fraction = mean(allPhases(2:end) ~= expectedNext);
end

function instrumentSignals(model)
signalSpecs = {
    "33",  1, "vout";
    "219", 1, "trigger";
    "78",  1, "qh1";
    "99",  1, "qh2";
    "120", 1, "qh3";
    "141", 1, "qh4";
};
for k = 1:size(signalSpecs, 1)
    blockPath = Simulink.ID.getFullName(model + ":" + signalSpecs{k, 1});
    instrumentBlockPort(blockPath, signalSpecs{k, 2}, signalSpecs{k, 3});
end
for phase = 1:4
    instrumentBlockPort(model + "/IL_Measurement" + phase, 1, "il" + phase);
end
end

function instrumentBlockPort(blockPath, portNumber, signalName)
ports = get_param(blockPath, "PortHandles");
portHandle = ports.Outport(portNumber);
lineHandle = get_param(portHandle, "Line");
if lineHandle ~= -1
    set_param(lineHandle, "Name", char(signalName));
end
Simulink.sdi.markSignalForStreaming(portHandle, "on");
end

function policyEval = summarizeR027Policies(rows)
valid = rows(rows.success, :);
policyEval = table();
if isempty(valid)
    return;
end
policies = unique(valid.policy, "stable");
for k = 1:numel(policies)
    r = valid(valid.policy == policies(k), :);
    policyEval = [policyEval; table( ... %#ok<AGROW>
        policies(k), string(r.policy_role(1)), logical(r.online_available_inputs_only(1)), ...
        height(r), mean(r.switching_regret_vs_best_in_run, "omitnan"), ...
        max(r.switching_regret_vs_best_in_run, [], "omitnan"), ...
        mean(r.selected_objective_score, "omitnan"), ...
        mean(r.undershoot_mV, "omitnan"), max(r.undershoot_mV, [], "omitnan"), ...
        mean(abs(r.final_vout_error_mV), "omitnan"), ...
        mean(r.skip_count_est, "omitnan"), mean(r.settle_time_us, "omitnan"), ...
        mean(r.final_phase_spacing_std_ns, "omitnan"), ...
        mean(r.base_score, "omitnan"), mean(r.score_settle005, "omitnan"), ...
        mean(r.score_settle010, "omitnan"), ...
        'VariableNames', {'policy','policy_role','online_available_inputs_only', ...
        'n_cases','mean_switching_regret','max_switching_regret', ...
        'mean_selected_objective_score','mean_undershoot_mV','max_undershoot_mV', ...
        'mean_abs_final_vout_error_mV','mean_skip_count','mean_settle_time_us', ...
        'mean_phase_spacing_std_ns','mean_base_score','mean_score_settle005','mean_score_settle010'})];
end
policyEval = sortrows(policyEval, ["mean_switching_regret","max_switching_regret"]);
end

function writeR027DryRunReport(plan, planPath, outputRoot, planMode)
reportPath = fullfile(outputRoot, "iqcot_r027_proxy_table_in_loop_matlab_dryrun_" + planMode + ".md");
fid = fopen(reportPath, "w", "n", "UTF-8");
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "# R027 MATLAB proxy table-in-loop dry run\n\n");
fprintf(fid, "Plan mode: `%s`.\n\n", planMode);
fprintf(fid, "Plan CSV: `%s`.\n\n", strrep(planPath, "\", "/"));
fprintf(fid, "Rows: `%d`.\n\n", height(plan));
fprintf(fid, "Policies: `%s`.\n\n", strjoin(unique(plan.policy, "stable"), "`, `"));
fprintf(fid, "This dry run did not execute Simulink. It verified that R027 CSV rows can be loaded by MATLAB and converted into delayed `Iph_ref_ts` cases.\n\n");
fprintf(fid, "Boundary: R027 dry-run and offline expected scores are not switching-level or hardware validation. AI remains a supervisory parameter scheduler.\n");
end

function writeR027SwitchingReport(rows, policyEval, resultPath, policyPath, reportPath, planMode)
fid = fopen(reportPath, "w", "n", "UTF-8");
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, "# R027 proxy table-in-loop switching validation\n\n");
fprintf(fid, "- Plan mode: `%s`\n", planMode);
fprintf(fid, "- Result CSV: `%s`\n", strrep(resultPath, "\", "/"));
fprintf(fid, "- Policy CSV: `%s`\n\n", strrep(policyPath, "\", "/"));
fprintf(fid, "This run uses only the derived Simulink model and delayed `Iph_ref_ts` profiles. It checks whether the R026 calibrated risk proxy ordering survives switching-level replay.\n\n");
fprintf(fid, "Executed rows: `%d`. Treat small `maxCases` runs as interface smoke tests, not complete R027 evidence.\n\n", height(rows));
if isempty(policyEval)
    fprintf(fid, "No successful policy rows were produced.\n");
    return;
end
fprintf(fid, "## Policy summary\n\n");
fprintf(fid, "| Policy | role | online inputs | mean regret | max regret | mean objective | mean undershoot mV | mean settle us |\n");
fprintf(fid, "|---|---|---:|---:|---:|---:|---:|---:|\n");
for k = 1:height(policyEval)
    fprintf(fid, "| `%s` | `%s` | %d | %.3f | %.3f | %.3f | %.3f | %.3f |\n", ...
        policyEval.policy(k), policyEval.policy_role(k), policyEval.online_available_inputs_only(k), ...
        policyEval.mean_switching_regret(k), policyEval.max_switching_regret(k), ...
        policyEval.mean_selected_objective_score(k), policyEval.mean_undershoot_mV(k), ...
        policyEval.mean_settle_time_us(k));
end
fprintf(fid, "\nBoundary: these are derived-model switching results, not hardware validation and not proof of global `T_slew` optimality. Posterior mode-aware rows remain upper-bound comparators, not deployable AI.\n");
end

function makeR027PolicyPlot(policyEval, figurePath)
if isempty(policyEval)
    return;
end
fig = figure(Visible="off", Position=[100 100 1150 560]);
cleanup = onCleanup(@() close(fig));
x = categorical(policyEval.policy);
x = reordercats(x, cellstr(policyEval.policy));
bar(x, [policyEval.mean_switching_regret policyEval.mean_selected_objective_score]);
grid on;
ylabel("Mean value");
legend("switching regret", "selected objective score", Location="best");
title("R027 proxy table-in-loop switching validation");
xtickangle(25);
exportgraphics(fig, figurePath, Resolution=180);
end
